services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: sh -c "npm install && npm start"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
